apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gitwriter-sc
  labels:
    app.kubernetes.io/part-of: hello-world
    carto.run/workload-name: gitwriter-sc
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - name: workload
        image: harbor.fbclouddemo.us/tap-packages/example-gitwriter-sc-gitwriter-sc@sha256:0422e0b4d6f3e82486d09bde55b6227379ae3c9fdad5536cd12017e6d228ead7
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: registry-credentials

