apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gitwriter-sc
  labels:
    app.kubernetes.io/part-of: hello-world
    carto.run/workload-name: gitwriter-sc
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - name: workload
        image: harbor.fbclouddemo.us/tap-packages/example-gitwriter-sc-gitwriter-sc@sha256:b1be5ce44abc27b017ddc6816a61cd976c699bc9ed01eed3206136d47d9c38ae
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: registry-credentials

